/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/pagos`; params?: Router.UnknownInputParams; } | { pathname: `/perfil-setup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/entrenar` | `/entrenar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/historial` | `/historial`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/descanso` | `/descanso`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ejercicios` | `/ejercicios`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/pagos`; params?: Router.UnknownOutputParams; } | { pathname: `/perfil-setup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/entrenar` | `/entrenar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/historial` | `/historial`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/descanso` | `/descanso`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ejercicios` | `/ejercicios`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/pagos${`?${string}` | `#${string}` | ''}` | `/perfil-setup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/entrenar${`?${string}` | `#${string}` | ''}` | `/entrenar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/historial${`?${string}` | `#${string}` | ''}` | `/historial${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/descanso${`?${string}` | `#${string}` | ''}` | `/descanso${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ejercicios${`?${string}` | `#${string}` | ''}` | `/ejercicios${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/pagos`; params?: Router.UnknownInputParams; } | { pathname: `/perfil-setup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/entrenar` | `/entrenar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/historial` | `/historial`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/descanso` | `/descanso`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ejercicios` | `/ejercicios`; params?: Router.UnknownInputParams; };
    }
  }
}
